Ensured we capture errors on async void to prevent application crashes
cogenta/puppeteer-sharp pull request #1
Opened 2018-11-07 14:55 UTC by Im5tu

As exceptions inside of async-void's can cause application crashes, this PR captures any exceptions and logs them if possible.

__Note:__ It's probably easier to view this PR in split mode

2018-11-08 11:15 UTC, tommymonk requested changes
Can you just sort out the line ending that have changed so we don't get pushback when creating PRs with upstream

2018-11-08 11:15 UTC, tommymonk commented on lib/PuppeteerSharp/Tracing.cs
> -using System.Collections.Generic;
Looks like this whole file has line ending changes ?

2018-11-08 13:29 UTC, Im5tu commented on lib/PuppeteerSharp/Tracing.cs
> -using System.Collections.Generic;
@tommymonk this should be resolved now

2018-11-09 16:20 UTC, tommymonk approved these changes
LGTM

2018-11-09 16:20 UTC, merged